### PR TITLE
clones the Recorded Request Body / improves the exception message

### PR DESCRIPTION
**Pull request by cleemansen**
See #6 for details.

1) clones the request body
2) improves the exception message a little bit

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
Good catch! 

Everything seems nice in your PR. The only thing missing is a test for the new buildMessage method. Can you provide one?

Thanks for your contribution!

**Comment by cs-victor-nascimento** [comment]
Ping?

**Comment by cleemansen** [comment]
Sry, just see your message... 
Ok, I will try to add a test for the `buildMessage` method soon..

**Comment by cs-victor-nascimento** [comment]
Hey @cleemansen! I've been looking into the code more carefully and there are a couple of things that we think would be better. 

We have refactored a bit your PR and provided a more  detailed message cleaning up the implementation in other aspects too. Right now we have the following message:

```java
Unexpected exception during assertion. No matcher found for request: 

> PATCH /head HTTP/1.1
> Content-Type: application/json; charset=utf-8
> Content-Length: 21
> Host: localhost:50191
> Connection: Keep-Alive
> Accept-Encoding: gzip
> User-Agent: okhttp/3.4.1

{"property": "value"}

Tried the following matchers:

1. Request matchers group:
 - method: is <DELETE>

 Failed because METHOD did NOT match.
 Expected: is <DELETE>
      but: was <PATCH>

2. Request matchers group:
 - method: is <PUT>

 Failed because METHOD did NOT match.
 Expected: is <PUT>
      but: was <PATCH>

3. Request matchers group:
 - method: is <PATCH>
 - request order: is <2>

 Failed because REQUEST ORDER did NOT match.
 Expected: is <2>
      but: was <1>

4. Request matchers group:
 - method: is <POST>

 Failed because METHOD did NOT match.
 Expected: is <POST>
      but: was <PATCH>

5. Request matchers group:
 - method: is <GET>
 - query parameters: is map containing [is "key"->an instance of java.lang.String]

 Failed because METHOD did NOT match.
 Expected: is <GET>
      but: was <PATCH>
```

We will probably go with that message and push it on a different PR. What do you think?

**Comment by cleemansen** [comment]
This better than before and much better than my approach! this is really helpful!

I miss one thing in your example: the assertion error of the request body!?

**Comment by cleemansen** [comment]
With your new implementation of the exception message a test for my introduced method `buildMessage` doesn't make any sense any more?! let me know if I misunderstood you @cs-victor-nascimento ...

**Comment by cs-victor-nascimento** [comment]
This is just an example of a test. It covers only a few of the possible messages. There is also a `Failed because BODY did NOT match.` and a `Failed because JSON BODY did NOT match.`.

So, I will accept your PR as is but will refactor a bit after that. Is that ok?

**Comment by cleemansen** [comment]
Yeah, of course that is ok! I'm looking forward to see and use your improvements soon!

Thanks and greetings
Clemens

**Pull request merged**
